# Generated by Django 6.0.5 on 2026-05-26 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0005_card_boost_card_source_image_url_character_movement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('1v1', '1 vs 1'), ('2v2', '2 vs 2')], default='1v1', max_length=10)),
                ('team_one_player', models.CharField(max_length=100)),
                ('team_two_player', models.CharField(max_length=100)),
                ('winner', models.CharField(choices=[('team_one', 'Team One'), ('team_two', 'Team Two')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('played_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.map')),
                ('team_one_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one_matches', to='wiki.character')),
                ('team_one_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_one_partner_matches', to='wiki.character')),
                ('team_two_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two_matches', to='wiki.character')),
                ('team_two_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_two_partner_matches', to='wiki.character')),
            ],
        ),
    ]
