# Generated by Django 6.0.5 on 2026-05-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='gamesets/')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('health', models.IntegerField()),
                ('attack_type', models.CharField(choices=[('melee', 'Melee'), ('ranged', 'Ranged')], max_length=20)),
                ('image', models.ImageField(upload_to='characters/')),
                ('game_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='wiki.gameset')),
            ],
        ),
    ]
