# Generated by Django 6.0.5 on 2026-05-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_character_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameset',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
