# Generated by Django 6.0.5 on 2026-05-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_gameset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AlterField(
            model_name='gameset',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gamesets/'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('versatile', 'Versatile'), ('scheme', 'Scheme')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='wiki.character')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('players_count', models.IntegerField(default=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='maps/')),
                ('game_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='wiki.gameset')),
            ],
        ),
        migrations.CreateModel(
            name='Sidekick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=1)),
                ('health', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sidekicks/')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidekicks', to='wiki.character')),
            ],
        ),
    ]
