# Generated by Django 6.0.5 on 2026-05-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_character_image_alter_gameset_cover_image_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='boost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='source_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='movement',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='character',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='special',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gameset',
            name='bgg_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='map',
            name='spaces_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='zone_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
